- name: Install Nginx
  sudo: yes
  yum: pkg=nginx state=latest

#Add templates
- name: Change to custom Nginx conf
  sudo: yes
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf

- name: Add default vhost
  sudo: yes
  template: src=default.conf.tpl dest=/etc/nginx/conf.d/default.conf

- name: Creates directory
  file: path=/srv/default state=directory

- name: Add default index page
  sudo: yes
  template: src=index.php.tpl dest=/srv/default/index.php


- name: Add SteveDeVeaux.com vhost
  sudo: yes
  template: src=com.stevedeveaux.conf.tpl dest=/etc/nginx/conf.d/com.stevedeveaux.conf

- service:
    name: nginx
    enabled: yes