- name: Install Nginx
  sudo: yes
  yum: pkg=nginx state=latest

# Add templates
- name: Change to custom Nginx conf
  sudo: yes
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf

- name: Add default vhost
  sudo: yes
  template: src=default.conf.tpl dest=/etc/nginx/conf.d/default.conf

- name: Creates directory
  file: path=/srv/default state=directory

- name: Add default index page
  sudo: yes
  template: src=index.php.tpl dest=/srv/default/index.php


- name: Add SteveDeVeaux.com vhost
  sudo: yes
  template: src=com.stevedeveaux.conf.tpl dest=/etc/nginx/conf.d/com.stevedeveaux.conf

- name: Add beyond-unity.co.uk vhost
  sudo: yes
  template: src=co.uk.beyondunity.conf.tpl dest=/etc/nginx/conf.d/co.uk.beyondunity.conf

- name: Add crazybulker.co.uk vhost
  sudo: yes
  template: src=co.uk.crazybulker.conf.tpl dest=/etc/nginx/conf.d/co.uk.crazybulker.conf

- name: Add the other crud
  sudo: yes
  template: src=virtual.conf.tpl dest=/etc/nginx/conf.d/virtual.conf

- service:
    name: nginx
    enabled: yes

- file:
    dest: /var/lib/php/7.1/session
    owner: nginx
    group: nginx
    recurse: yes

- file:
    dest: /var/lib/php/7.1/wsdlcache
    owner: nginx
    group: nginx
    recurse: yes

- file:
    dest: /var/lib/php/7.1/opcache
    owner: nginx
    group: nginx
    recurse: yes


- name: Mount up device by label
  mount:
    path: /srv
    src: /dev/xvdh
    fstype: ext4
    state: present